In [1]:
import json
import requests
import pandas as pd
import numpy as np
import datetime
from bokeh.plotting import figure, show
from bokeh.io import output_notebook, push_notebook, show
from bokeh.layouts import row
from bokeh.plotting import figure
from ipywidgets import interact
import os

In [13]:
def recolector(sy1,sm1,sd1,ey1,em1,ed1):
        #read file with current year data
        data= pd.read_csv(r'C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2021_column_ytd.csv')
        data=data.drop(['Unnamed: 0'], axis=1)

        #timeframe you want to include, inputs of the function
        start_date= datetime.datetime(sy1,sm1,sd1)
        end_date=datetime.datetime(ey1, em1,ed1)
        delta=(end_date-start_date).days
        datelist=pd.date_range(start_date, periods=delta).strftime("%Y%m%d").tolist()
        data1=[]
        
        for x in datelist:
            JSONContent = requests.get("https://api.aafm.cl/publicDailyStatistics/" + x).json()
            if 'error' not in JSONContent:
                data1.append(JSONContent)

        for x in range(len(datelist)):
            for y in range(len(data1[x])):
                data1[x][y]["fecha"]=datelist[x]

        subdatos=[]
        for x in range(len(datelist)):
                for y in range(len(data1[x])):
                        subdatos.append([data1[x][y]['administratorName'], 
                             data1[x][y]['fundRUN'], 
                             data1[x][y]['fundName'], 
                             data1[x][y]['fundSeries'], 
                             data1[x][y]['netPatrimony'], 
                             data1[x][y]['efectivePatrimony'], 
                             data1[x][y]['installmentsInCirculation'], 
                             data1[x][y]['providedInstallments'], 
                             data1[x][y]['providedFlow'], 
                             data1[x][y]['rescuedInstallments'],
                             data1[x][y]['rescuedFlow'], 
                             data1[x][y]['installmentValue'],
                             data1[x][y]['totalParticipants'],
                             data1[x][y]['institutionalParticipants'],
                             data1[x][y]['otherParticipants'],
                             data1[x][y]['APV'],
                             data1[x][y]['aafmCategory'],
                             data1[x][y]['svsCategory'],
                             data1[x][y]['svsCategoryId'],
                             data1[x][y]['currency'],
                             data1[x][y]['bloombergCode'],
                             data1[x][y]['pensionFunds'],
                             data1[x][y]['fixedRemuneration'],
                             data1[x][y]['variableRemuneration'],
                             data1[x][y]['affectedExpenses'],
                             data1[x][y]['unaffectedExpenses'],
                             data1[x][y]['investmentCommission'],
                             data1[x][y]['rescuedCommission'],
                             data1[x][y]['fecha']])

        df=pd.DataFrame(subdatos, columns=['administratorName','fundRUN',
         'fundName',
         'fundSeries',
         'netPatrimony',
         'efectivePatrimony',
         'installmentsInCirculation',
         'providedInstallments',
         'providedFlow',
         'rescuedInstallments',
         'rescuedFlow',
         'installmentValue',
         'totalParticipants',
         'institutionalParticipants',
         'otherParticipants',
         'APV',
         'aafmCategory',
         'svsCategory',
         'svsCategoryId',
         'currency',
         'bloombergCode',
         'pensionFunds',
         'fixedRemuneration',
         'variableRemuneration',
         'affectedExpenses',
         'unaffectedExpenses',
         'investmentCommission',
         'rescuedCommission',
         'fecha'])

        data2=data.append(df,ignore_index=True)
        data2.to_csv(r'C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2021_column_ytd.csv')
        #in case you are starting a new year
        #df.to_csv(r'C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2021_column_ytd.csv')
        #data3= pd.read_csv(r'C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2020_column_ytd_1.csv')
        
        #rename and remove existing file, to maintain file name.
        os.remove('C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2021_column_ytd.csv')
        os.rename(r'C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2021_column_ytd_1.csv',r'C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2021_column_ytd.csv')

In [16]:
data= pd.read_csv(r'C:\Users\bloomberg\Python\FFMM\Fondos_Mutuos_2021_column_ytd.csv')
max=data['fecha'].max()
max

20210213

In [18]:
data.head()

,Unnamed: 0,administratorName,fundRUN,fundName,fundSeries,netPatrimony,efectivePatrimony,installmentsInCirculation,providedInstallments,providedFlow,...,currency,bloombergCode,pensionFunds,fixedRemuneration,variableRemuneration,affectedExpenses,unaffectedExpenses,investmentCommission,rescuedCommission,fecha
0,0,BANCHILE,8023-3,HORIZONTE,B,4.623336e+09,4.623336e+09,9.657302e+04,0.0,0.0,...,P,BCHHORB CI,N,126670.0,0.0,0.0,0.0,0.0,0.0,20210101
1,1,BANCHILE,8023-3,HORIZONTE,BCH,6.827597e+10,6.827598e+10,5.479200e+07,0.0,0.0,...,P,BCHEMBC CI,N,0.0,0.0,0.0,0.0,0.0,0.0,20210101
2,2,BANCHILE,8023-3,HORIZONTE,BPLUS,8.210597e+08,8.210597e+08,3.474958e+05,0.0,0.0,...,P,NaN,N,13497.0,0.0,0.0,0.0,0.0,0.0,20210101
3,3,BANCHILE,8023-3,HORIZONTE,L,2.011615e+10,2.011615e+10,1.188652e+07,0.0,0.0,...,P,NaN,N,1047196.0,0.0,0.0,0.0,0.0,0.0,20210101
4,4,BANCHILE,8023-3,HORIZONTE,M,3.789891e+10,3.789891e+10,8.614187e+05,0.0,0.0,...,P,NaN,N,1729931.0,0.0,0.0,0.0,0.0,0.0,20210101

In [15]:
recolector(2021,1,1,2021,2,14)